public enum MessageType {
    TEXT,
    NEWUSER,
    DISCONNECT,
    GAMELIST,
    CREATE_GAME,
    REQUEST_GAMES,
    GAME_WAITING,
    GAME_LIST,
    JOIN_GAME,
    GAME_STARTED,
    BOARD_UPDATE,
    GAME_MOVE,
    GAME_OVER,
    MOVE,
    TURN,
    INVALID_MOVE,
    PLAYER_ID
}
